[package]
name = "xml2json"
version = "0.3.0"
edition = "2021"
authors = ["uvlad7 <uvlad7@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rb-sys = { version = "*", default-features = false, features = ["ruby-static", "stable-api-compiled-fallback"] }
magnus = { version = "0.5.5" }
xml2json-rs = "1.0.1"
